{% set version = "1.1-38" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-lme4
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lme4_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lme4/lme4_{{ version }}.tar.gz
  sha256: 97f895c10053ea178a116e2c5a3095208fc54ff2b67be3351faab9a6608c8cc7

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-boot                       # [build_platform != target_platform]
    - r-lattice                    # [build_platform != target_platform]
    - r-mass                       # [build_platform != target_platform]
    - r-matrix >=1.2_3             # [build_platform != target_platform]
    - r-minqa >=1.1.15             # [build_platform != target_platform]
    - r-nlme >=3.1_123             # [build_platform != target_platform]
    - r-nloptr >=1.0.4             # [build_platform != target_platform]
    - r-rcpp >=0.10.5              # [build_platform != target_platform]
    - r-rcppeigen >=0.3.3.9.4      # [build_platform != target_platform]
    - r-reformulas >=0.3.0         # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-boot
    - r-codetools
    - r-lattice
    - r-mass
    - r-matrix >=1.2_3
    - r-minqa >=1.1.15
    - r-nlme >=3.1_123
    - r-nloptr >=1.0.4
    - r-rcpp >=0.10.5
    - r-rcppeigen >=0.3.3.9.4
    - r-reformulas >=0.3.0
  run:
    - r-base
    - r-boot
    - r-lattice
    - r-mass
    - {{ pin_compatible('r-matrix', exact=True) }}
    - r-minqa >=1.1.15
    - r-nlme >=3.1_123
    - r-nloptr >=1.0.4
    - r-rcpp >=0.10.5
    - r-rcppeigen >=0.3.3.9.4
    - r-reformulas >=0.3.0

test:
  requires:
    - r-testthat
    - r-codetools
  source_files:
    - tests/
  commands:
    - $R -e "library('lme4')"                                                                           # [not win]
    - $R -e "testthat::test_dir('tests/testthat/', package='lme4', load_package='installed')"           # [not win]
    - "\"%R%\" -e \"library('lme4')\""                                                                  # [win]
    - "\"%R%\" -e \"testthat::test_dir('tests/testthat/', package='lme4', load_package='installed')\""  # [win]

about:
  home: https://github.com/lme4/lme4/
  license: GPL-2.0-or-later
  summary: Fit linear and generalized linear mixed-effects models. The models and their components are represented using S4 classes and methods.  The core computational algorithms are implemented using the 'Eigen' C++ library for numerical linear algebra and 'RcppEigen' "glue".
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
