{% set version = '1.1-18-1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lme4
  version: {{ version|replace("-", "_") }}

source:
  fn: lme4_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/lme4_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lme4/lme4_{{ version }}.tar.gz
  sha256: 982af02f33d40de88e3ec358eceec74576c8b839a526587760477e3495235905

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-matrix >=1.2_1
    - r-rcpp >=0.10.5
    - r-rcppeigen
    - r-lattice
    - r-minqa >=1.1.15
    - r-nlme >=3.1_123
    - r-nloptr >=1.0.4
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mass
    - r-matrix >=1.2_1
    - r-rcpp >=0.10.5
    - r-rcppeigen
    - r-lattice
    - r-minqa >=1.1.15
    - r-nlme >=3.1_123
    - r-nloptr >=1.0.4

test:
  commands:
    - $R -e "library('lme4')"           # [not win]
    - "\"%R%\" -e \"library('lme4')\""  # [win]

about:
  home: https://github.com/lme4/lme4/ http://lme4.r-forge.r-project.org/
  license: GPL (>= 2)
  summary: Fit linear and generalized linear mixed-effects models. The models and their components
    are represented using S4 classes and methods.  The core computational algorithms
    are implemented using the 'Eigen' C++ library for numerical linear algebra and 'RcppEigen'
    "glue".
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
