{% set version = '1.1-13' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lme4
  version: {{ version|replace("-", "_") }}

source:
  fn: lme4_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/lme4_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/lme4/lme4_{{ version }}.tar.gz
  sha256: 5fa8b63d15882d153ee105d399b559dd942d97b2e6e7deae3802f41cc451448e

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-mass
    - r-matrix >=1.1.1
    - r-rcpp >=0.10.5
    - r-rcppeigen
    - r-lattice
    - r-minqa >=1.1.15
    - r-nlme >=3.1_123
    - r-nloptr >=1.0.4

  run:
    - r-base
    - r-mass
    - r-matrix >=1.1.1
    - r-rcpp >=0.10.5
    - r-rcppeigen
    - r-lattice
    - r-minqa >=1.1.15
    - r-nlme >=3.1_123
    - r-nloptr >=1.0.4

test:
  commands:
    - $R -e "library('lme4')"  # [not win]
    - "\"%R%\" -e \"library('lme4')\""  # [win]

about:
  home: https://github.com/lme4/lme4/ http://lme4.r-forge.r-project.org/
  license: GPL (>= 2)
  summary: Fit linear and generalized linear mixed-effects models. The models and their components
    are represented using S4 classes and methods.  The core computational algorithms
    are implemented using the 'Eigen' C++ library for numerical linear algebra and 'RcppEigen'
    "glue".
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
