{% set version = "1.1-34" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lme4
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lme4_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lme4/lme4_{{ version }}.tar.gz
  sha256: e872e150d2b3da8898915ce2d5a39bdf4bbd496ed937693c206dd4d2f2ec6aad

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-minqa                    # [build_platform != target_platform]
    - r-boot                     # [build_platform != target_platform]
    - r-statmod                  # [build_platform != target_platform]
    - r-nlme                     # [build_platform != target_platform]
    - r-rcppeigen                # [build_platform != target_platform]
    - r-lattice                  # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - r-nloptr                   # [build_platform != target_platform]
    - r-mass                     # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-statmod
    - r-rcpp >=0.10.5
    - r-rcppeigen
    - r-boot
    - r-lattice
    - r-minqa >=1.1.15
    - r-nlme >=3.1_123
    - r-nloptr >=1.0.4
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mass
    - r-statmod
    - r-rcpp >=0.10.5
    - r-rcppeigen
    - r-boot
    - r-lattice
    - r-minqa >=1.1.15
    - r-nlme >=3.1_123
    - r-nloptr >=1.0.4

test:
  commands:
    - $R -e "library('lme4')"           # [not win]
    - "\"%R%\" -e \"library('lme4')\""  # [win]

about:
  home: https://github.com/lme4/lme4/
  license: GPL-2.0-or-later
  summary: Fit linear and generalized linear mixed-effects models. The models and their components are represented using S4 classes and methods.  The core computational algorithms are implemented using the 'Eigen' C++ library for numerical linear algebra and 'RcppEigen' "glue".
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: lme4
# Version: 1.1-21
# Title: Linear Mixed-Effects Models using 'Eigen' and S4
# Authors@R: c( person("Douglas","Bates", role="aut", comment=c(ORCID="0000-0001-8316-9503")), person("Martin","Maechler", role="aut", comment=c(ORCID="0000-0002-8685-9910")), person("Ben","Bolker",email="bbolker+lme4@gmail.com", role=c("aut","cre"), comment=c(ORCID="0000-0002-2127-0443")), person("Steven","Walker",role="aut", comment=c(ORCID="0000-0002-4394-9078")), person("Rune Haubo Bojesen","Christensen", role="ctb", comment=c(ORCID="0000-0002-4494-3399")), person("Henrik","Singmann", role="ctb", comment=c(ORCID="0000-0002-4842-3657")), person("Bin", "Dai", role="ctb"), person("Fabian", "Scheipl", role="ctb", comment=c(ORCID="0000-0001-8172-3603")), person("Gabor", "Grothendieck", role="ctb"), person("Peter", "Green", role="ctb", comment=c(ORCID="0000-0002-0238-9852")), person("John", "Fox", role="ctb") )
# Contact: LME4 Authors <lme4-authors@lists.r-forge.r-project.org>
# Description: Fit linear and generalized linear mixed-effects models. The models and their components are represented using S4 classes and methods.  The core computational algorithms are implemented using the 'Eigen' C++ library for numerical linear algebra and 'RcppEigen' "glue".
# Depends: R (>= 3.2.0), Matrix (>= 1.2-1), methods, stats
# LinkingTo: Rcpp (>= 0.10.5), RcppEigen
# Imports: graphics, grid, splines, utils, parallel, MASS, lattice, boot, nlme (>= 3.1-123), minqa (>= 1.1.15), nloptr (>= 1.0.4)
# Suggests: knitr, rmarkdown, PKPDmodels, MEMSS, testthat (>= 0.8.1), ggplot2, mlmRev, optimx (>= 2013.8.6), gamm4, pbkrtest, HSAUR2, numDeriv, car, dfoptim
# VignetteBuilder: knitr
# LazyData: yes
# License: GPL (>= 2)
# URL: https://github.com/lme4/lme4/
# BugReports: https://github.com/lme4/lme4/issues
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2019-03-05 17:34:33 UTC; bolker
# Author: Douglas Bates [aut] (<https://orcid.org/0000-0001-8316-9503>), Martin Maechler [aut] (<https://orcid.org/0000-0002-8685-9910>), Ben Bolker [aut, cre] (<https://orcid.org/0000-0002-2127-0443>), Steven Walker [aut] (<https://orcid.org/0000-0002-4394-9078>), Rune Haubo Bojesen Christensen [ctb] (<https://orcid.org/0000-0002-4494-3399>), Henrik Singmann [ctb] (<https://orcid.org/0000-0002-4842-3657>), Bin Dai [ctb], Fabian Scheipl [ctb] (<https://orcid.org/0000-0001-8172-3603>), Gabor Grothendieck [ctb], Peter Green [ctb] (<https://orcid.org/0000-0002-0238-9852>), John Fox [ctb]
# Maintainer: Ben Bolker <bbolker+lme4@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-03-05 22:40:10 UTC
