appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: aRsq2AKU8vu2GjkZU0Rc2HgUnuCGxQXrGolvqroEkFfpTYrjAckwY+GuNFNl0/+rngNMlgcwjAlkYUZhUOaL7sfYyBQa6MOwZAq2+ngHtBEsxZzfRntvzjuNYzlgM4m/X/HHv+BV0ezuxKVAGCDUWLWfWEIScXID1U4NQJv594fJpkAUpG1TkGgFuhouxYiMDN02GTFF5HqXZBDy2w7I38mABAH23fIrIhf5siEECyQKl1CV/bCduxML1Wy5V/UWdghI1qx3XmXgW+KRb2h7kINUDhc7yqbEpTbJ4rTRj9Y15L/pDI1/z755hW6Re5dWGmcn70e4ozyyglihY0mvuH9Mcixqjny/Oro7tXlIopqynJW69KLUoxzH7fY4TS8Chng+lMmkEwf2ueNpUk3elcjjBHPN0GdKbFBtJXUKr8W02OhKIofPTjX07tNHC1cyZiMZJFrT/VVsrryCxHZcOo/F3cFfyzsLebTGdYmb5LiHvipqUESBr/xiBQ+Q723IaaM/Nj8BLaRaPCl4FAed3/1vPorZAM6TcL+nAC3OCu35yZDkT8bdc7ooxuCoAgxinvhtqx7m09CfQclrq6VTotG0fT5G0X32fwihTSlw3qguBFXUoxVRCzXrv1nUXKZShsAwKWNuqrpaYLbKT1sOSK06l71I+NTez8jOuCa02CM=
conda_forge_output_validation: true
